"""rename is_active to is_working in work_schedules

Revision ID: 74a67a414265
Revises: fb0a28f50790
Create Date: 2026-02-25 23:18:37.196455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a67a414265'
down_revision: Union[str, Sequence[str], None] = 'fb0a28f50790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_schedules', sa.Column('is_working', sa.Boolean(), nullable=True))
    op.drop_column('work_schedules', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_schedules', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('work_schedules', 'is_working')
    # ### end Alembic commands ###
