"""add notify_email to masters

Revision ID: 8771eca30865
Revises: d834703513ed
Create Date: 2026-04-21 21:57:45.099897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8771eca30865'
down_revision: Union[str, Sequence[str], None] = 'd834703513ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('notify_email', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masters', 'notify_email')
    # ### end Alembic commands ###
