"""add client_social, make client_phone nullable

Revision ID: d834703513ed
Revises: fb19c4fed6ca
Create Date: 2026-04-19 13:58:10.913048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd834703513ed'
down_revision: Union[str, Sequence[str], None] = 'fb19c4fed6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('client_social', sa.String(), nullable=True))
    op.alter_column('bookings', 'client_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'client_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('bookings', 'client_social')
    # ### end Alembic commands ###
