"""add telegram_id to masters

Revision ID: fb19c4fed6ca
Revises: 0ab2b527b8c0
Create Date: 2026-04-16 18:38:41.008854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb19c4fed6ca'
down_revision: Union[str, Sequence[str], None] = '0ab2b527b8c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('telegram_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'masters', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'masters', type_='unique')
    op.drop_column('masters', 'telegram_id')
    # ### end Alembic commands ###
